# Generated by Django 3.1.3 on 2020-12-02 07:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201202_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_data',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 2, 7, 30, 2, 982820, tzinfo=utc)),
        ),
    ]
