# Generated by Django 3.1.3 on 2020-12-02 12:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201202_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_data',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 2, 12, 13, 55, 161398, tzinfo=utc)),
        ),
    ]
